export const CONFIG = {
    BASS_OCTAVE_DROP: -24,
    AUDITION_DURATION_SEC: 0.8,
    ATTACK_TIME: 0.05,
    RELEASE_TIME: 0.1,
    SUSTAIN_LEVEL: 0.15,
    A4_MIDI: 69,
    A4_FREQ: 440,
    COMPRESSOR_THRESHOLD: -24,
    COMPRESSOR_KNEE: 30,
    COMPRESSOR_RATIO: 12,
    COMPRESSOR_ATTACK: 0.003,
    COMPRESSOR_RELEASE: 0.25,
    MIDI_CHORD_VELOCITY: 80,
    MIDI_BASS_VELOCITY: 90,
    DRAG_OFFSET_X: 20,
    DRAG_OFFSET_Y: 20
};